  name: Release

  on:
    push:
      tags:
        - 'v*'

  permissions:
    contents: write

  jobs:
    release:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.24'

        - name: Cache Go modules
          uses: actions/cache@v3
          with:
            path: |
              ~/.cache/go-build
              ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-go-

        - name: Build binary
          run: |
            go build -ldflags "-X main.version=${{ github.ref_name }}" -o domain-checker

        - name: Create GitHub Release
          uses: ncipollo/release-action@v1
          with:
            tag: ${{ github.ref_name }}
            name: Release ${{ github.ref_name }}
            body: |
              Automated release of version ${{ github.ref_name }}.
            draft: false
            prerelease: false

        - name: Log into Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: |
              mallox/domain-checker:latest
              mallox/domain-checker:${{ github.ref_name }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
