name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - go.mod
      - go.sum
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - go.mod
      - go.sum

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Go modules
        id: go-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Download modules (if cache miss)
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Run tests
        run: go test -v ./...